### PR TITLE
Update readme instructions

### PR DESCRIPTION
**Pull request by Eroldin**
Added a additional option for xOBSE in proton, which allows for the use of the Oblivion Launcher.

### CODE REVIEW

**Comment by katawful** [comment]
The file change method was removed as it is invasive, and doesn't really have any reason to exist. OblivionLauncher.exe has few features, and the rename feature is in-line with how other Steam script extenders work

**Comment by llde** [comment]
You can 't modify xOBSE launcher using the offset from the OBSE 21 launcher.

**Comment by Eroldin** [comment]
@llde That's strange... I did this with xOBSE and it works fine. Granted, I used the xOBSE executable from 22.4 when I modified the launcher so I do not know if it works with version 22.5...

**Comment by llde** [comment]
It worked fine becouse xOBSE loader already allow to load the Steam executable directly. But who know what that command actually modified

**Comment by Eroldin** [comment]
I understand the issue, I will close the pull request then.

**Pull request closed without merging**
